version: '2'

services: 
  web:
    image: healthplatforms/webserver
#    ports:
#      - "8080:80" 
    volumes:
      - ./templates:/etc/nginx/templates 
  db: 
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: mypasswd 
#  adminer: 
#    image: adminer 
#    restart: always 
#    ports: 
#      - 8080:80    
volumes:
  templates:
